### ISSUE TITLE
Could not find com.paytm.appinvokesdk:appinvokesdk:1.6.6.

### ISSUE THREAD

**Issue by abhijitkumar2023** [paytm/paytm-allinonesdk-react-native#13]
i am using react native 0.71.5 version. please tell me how to implement paytm gatewaye.

**Comment by hambalharis** [comment]
getting the same error. did you find a solution?

**Comment by aayushanand99** [comment]
Hi Did you guys resolve it? facing the same issue here

**Comment by abhijitkumar2023** [comment]
I got solution from paytm devteam.

allprojects {
 repositories {
     ...
     maven {
         url "https://artifactory.paytm.in/libs-release-local"
    }
  }
}

In place of three dot(...) add two line

allprojects {
  repositories {
    google()           // add this line
    mavenCentral()    // add this line
     maven {
            url "https://artifactory.paytm.in/libs-release-local"
        }
  }
}

now it is working fine .

**Comment by mdrajibsk8** [comment]
My build.gradle look like this - 

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.6.0"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://artifactory.paytm.in/libs-release-local"
        }
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

`Still giving me this error - Could not find com.paytm.appinvokesdk:appinvokesdk:1.6.15.`

Tried adding this in app/build.gradle, still same issue

**Comment by rahul2bisht** [comment]
Hi,
Please add the dependancies on build.gradle file as below to resolve the issue

allprojects {
repositories {
google() // add this line
mavenCentral() // add this line
maven {
url "https://artifactory.paytm.in/libs-release-local"
}
}
}
