### ISSUE TITLE
Could not build Objective-C module 'paytm_allinone_react_native'

### ISSUE THREAD

**Issue by ankitpatel7225** [paytm/paytm-allinonesdk-react-native#16]
Got an issue while installing library in new RN 0.72.4.
// IOS
       SwiftEmitModule normal x86_64 Emitting\ module\ for\ paytm_allinone_react_native (in target 'paytm_allinone_react-native' from project 'Pods')
![Screenshot 2023-11-09 at 7 21 32 PM](https://github.com/paytm/paytm-allinonesdk-react-native/assets/70798737/afb8f147-fbd9-4f36-bc27-725c59bdc03c)

React Native Version : 0.72.4
X Code Version : 14.2

 I have already re install every thing twice and clear DerivedData as well.

**Comment by vaibhavdagar** [comment]
Were you able to solve this?

**Comment by rahul2bisht** [comment]
This can be fixed by adding the following line in the podfile of the project.

installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      end
end

**Comment by mohdabid0786** [comment]
Did anyone got any solutions for this issue, when running into react-native facing into Simulator using Xcode 15.0.1, iOS version 17.0 in Apple M1 chip. Please if anyone got solution, update here.

**Comment by navdeep-1999** [comment]
Did anyone found the solution for the same?

**Comment by ankitpatel7225** [comment]
> Did anyone got any solutions for this issue, when running into react-native facing into Simulator using Xcode 15.0.1, iOS version 17.0 in Apple M1 chip. Please if anyone got solution, update here.

[rahul2bisht](https://github.com/rahul2bisht) is Solution is working. Just add this line in your pod file like this.

``` 
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      end
    end
  end
  ```

And comment on this error manually: "Unsupported Swift architecture." This solution was provided by the Paytm team. The logic behind this, according to the Paytm team, is that Xcode is generating unnecessary log files, causing this issue.

cc: @navdeep-1999 

Closing this as it has been resolved.

**Comment by vcankur** [comment]
face same issue with react native 0.61.5 on m1

**Comment by prasad456** [comment]
@rahul2bisht answer not working for me
@ankitpatel7225 I tried it remains the same issue
